# frozen_string_literal: true

# One-off travel crossings relocated verbatim from mapdb StringProcs.
#
# EMPTY BY DESIGN. Every edge in both games is declarative schema now, so
# there is nothing to relocate and this file defines no crossings.
#
# The registry stays because the conversion pipeline still needs somewhere
# to put a proc it cannot convert: gen_crossings.rb relocates any such body
# here so the edge keeps working while the recognizer or manual schema for
# it is written. Landing here is a signal, not a resting place - a block in
# this file is an edge waiting to be converted.
#
# GENERATED by tools/gen_crossings.rb; it fills the per-game sections below
# and rewrites only its own game's section.

module Lich
  module Common
    module MapEngine
      module UniqueCrossings
        REGISTRY = {} unless const_defined?(:REGISTRY, false)

        def self.define(name, &block)
          REGISTRY[name.to_s] = block
        end

        def self.known?(name)
          REGISTRY.key?(name.to_s)
        end

        def self.run(name)
          block = REGISTRY[name.to_s]
          raise StepFailed, "unknown crossing #{name.inspect}" unless block
          block.call
          true
        end

        # ===== BEGIN gs crossings (generated) =====
        # ===== END gs crossings =====
        # ===== BEGIN dr crossings (generated) =====
        # ===== END dr crossings =====
      end
    end
  end
end
