# frozen_string_literal: true

# rubocop:disable all
# One-off travel crossings relocated verbatim from mapdb StringProcs.
#
# GENERATED by tools/gen_crossings.rb - each block below is the exact Ruby
# a map edge used to carry as an eval'd string. Living here it is reviewed,
# diffable Lich code; the mapdb references it by name via
#   { "strategy" => "unique_crossing", "name" => "crossing[_dr]_ROOM_DEST" }
# Sections are per-game; a generator run replaces only its own section.
# Refactor blocks into proper strategies at leisure.

module Lich
  module Common
    module MapEngine
      module UniqueCrossings
        REGISTRY = {} unless const_defined?(:REGISTRY, false)

        def self.define(name, &block)
          REGISTRY[name.to_s] = block
        end

        def self.known?(name)
          REGISTRY.key?(name.to_s)
        end

        def self.run(name)
          block = REGISTRY[name.to_s]
          raise StepFailed, "unknown crossing #{name.inspect}" unless block
          block.call
          true
        end

        # ===== BEGIN gs crossings (generated) =====

        define('crossing_27638_27639') do # 27638:27639 27639:27638
          if UserVars.Peregrine; UserVars.Peregrine.each{|c| fput "#{c}" } end
        end
        # ===== END gs crossings =====
        # ===== BEGIN dr crossings (generated) =====

        define('crossing_dr_473_1375') do # 473:1375
          if Script.exists?('bescort') then start_script('bescort', ['faldesu', 'crossing']);wait_while{running?('bescort')};else echo 'CREATE A SCRIPT CALLED UDC TO REMOVE ARMOR';start_script ('udc');wait_while{ running?('udc') };pause;fput 'dive river';pause;waitrt?;fput 'swim s';pause;waitrt?;fput 'swim s';pause;waitrt?;fput 'swim s';pause;waitrt?;fput 'swim s';pause;waitrt?;fput 'swim s';pause;waitrt?;fput 'swim s';pause;waitrt?;fput 'swim s';pause;waitrt?;fput 'swim s';pause;waitrt?;fput 'swim s';pause;waitrt?;fput 'swim sw';pause;waitrt?;fput 'swim se';pause;waitrt?;fput 'swim se';pause;waitrt?;fput 'swim se';pause;waitrt?;fput 'swim se';pause;waitrt?;fput 'swim se';pause;waitrt?;fput 'swim se';pause;waitrt?;fput 'swim se';pause;waitrt?;fput 'swim se';pause;waitrt?;fput 'swim se';pause;waitrt?;fput 'climb bridge';start_script ('rdc');wait_while{ running?('rdc') };echo 'CREATE A SCRIPT CALLED RDC TO WEAR ARMOR' end
        end

        define('crossing_dr_1375_473') do # 1375:473
          if Script.exists?('bescort') then start_script('bescort', ['faldesu', 'haven']);wait_while{running?('bescort')}; else echo 'YOU CAN CREATE A SCRIPT NAMED UDC TO TAKE ALL ARMOR OFF';start_script ('udc');wait_while{ running?('udc') };fput 'dive river';pause;waitrt?;fput 'swim n';pause;waitrt?;fput 'swim n';pause;waitrt?;fput 'swim n';pause;waitrt?;fput 'swim n';pause;waitrt?;fput 'swim n';pause;waitrt?;fput 'swim n';pause;waitrt?;fput 'swim n';pause;waitrt?;fput 'swim n';pause;waitrt?;fput 'swim nw';pause;waitrt?;fput 'swim ne';pause;waitrt?;fput 'swim ne';pause;waitrt?;fput 'swim ne';pause;waitrt?;fput 'swim ne';pause;waitrt?;fput 'swim ne';pause;waitrt?;fput 'swim ne';pause;waitrt?;fput 'swim ne';pause;waitrt?;fput 'swim ne';pause;waitrt?;fput 'swim ne';pause;waitrt?;fput 'swim ne';pause;waitrt?;fput 'climb bridge';echo 'YOU CAN CREATE A SCRIPT CALLED RDC TO PUT ALL ARMOR ON';start_script ('rdc');wait_while{ running?('rdc') } end
        end

        define('crossing_dr_2249_2904') do # 2249:2904
          if Script.exists?('bescort'); start_script('bescort', ['gondola', 'south']); wait_while{running?('bescort')}; else; result = dothistimeout 'go gondola', 10, /^There is no wooden gondola here.| Gondola, Cab North/; unless result =~ /Gondola, Cab North/; echo 'waiting for the gondola...'; waitfor 'The gondola stops on the platform and the door silently swings open.'; move 'go gondola'; end;  move 'south'; waitfor 'With a soft bump, the gondola comes to a stop at its destination.'; move out; end
        end

        define('crossing_dr_2904_2249') do # 2904:2249
          if Script.exists?('bescort'); start_script('bescort', ['gondola', 'north']); wait_while{running?('bescort')}; else;result = dothistimeout 'go gondola', 10, /^There is no wooden gondola here.|Gondola, Cab South/; unless result =~ /Gondola, Cab South/; echo 'waiting for the gondola...'; waitfor 'The gondola stops on the platform and the door silently swings open.'; move 'go gondola'; end; move 'north'; waitfor 'With a soft bump, the gondola comes to a stop at its destination.'; move out; end
        end

        define('crossing_dr_4540_4543') do # 4540:4543
          result = dothistimeout 'go stone wall', 2, /I could not find what you were referring to.|Seord Kerwaith, Squat Cavern/; unless result =~ /Seord Kerwaith, Squat Cavern/; fput 'turn torch'; pause 1; move 'go stone wall'; end
        end

        define('crossing_dr_4543_4540') do # 4543:4540
          result = dothistimeout 'go stone wall', 2, /^I could not find what you were referring to.|Cragstone Vale, Tunnel/; unless result =~ /Cragstone Vale, Tunnel/; fput 'turn basin'; pause 1; move 'go stone wall'; end
        end

        define('crossing_dr_5072_4794') do # 5072:4794
          DRC.bput('open door',/already open/,/slowly lifting the door/);DRC.bput('climb steep tunnel in door','Ratha')
        end

        define('crossing_dr_5191_12660') do # 5191:12660
          pause 1;DRC.bput('search', 'Roundtime');pause 4;DRC.bput('go narrow gap','This narrow trail through')
        end

        define('crossing_dr_7633_7647') do # 7633:7647
          start_script('weararmor', ['swimming']) if DRSkill.getmodrank('Athletics') < 240; wait_while{ running?('weararmor') }; move 'go bank'
        end

        define('crossing_dr_7639_7643') do # 7639:7643
          fput 'search rocky ledge'; move 'climb shrub';fput 'peer path'
          dir = matchfindword "Peering closely at a faint path, you realize you would need to head ?"
          move 'down'
          sleep 2 if running?('agoto')
          move dir
        end

        define('crossing_dr_7651_7658') do # 7651:7658
          start_script('weararmor') if DRSkill.getmodrank('Athletics') < 240; wait_while{ running?('weararmor') }; move 'go bank'
        end

        define('crossing_dr_8060_8082') do # 8060:8082
          fput 'peer church'
          dir = matchfindword "You recall that the path you traced to the church lies to the ?","you manage to spy a suitable path to the ?"
          sleep 2
          move 'climb trunk'
          sleep 2 if running?('agoto')
          move dir
        end

        define('crossing_dr_8837_8841') do # 8837:8841
          fput 'go river
           west'; pause; waitrt?; fput 'go island'
        end

        define('crossing_dr_8841_8837') do # 8841:8837
          fput 'go river
           east'; pause; waitrt?; fput 'go bank'
        end

        define('crossing_dr_12132_12131') do # 12132:12131
          echo Room[Room.current.id].inspect
        end

        define('crossing_dr_19075_19389') do # 19075:19389
          move w; move w; move w;
        end

        define('crossing_dr_19389_19075') do # 19389:19075
          move e; move e; move e;
        end

        define('crossing_dr_34400_34404') do # 34400:34404 34404:34400
          loop{fput 'turn sconce';status = matchfindword 'you ? down','You ? up';pause;break if status == 'pull'};move 'go door'
        end
        # ===== END dr crossings =====
      end
    end
  end
end
# rubocop:enable all
