{
  schema_version: 3,
  name: "fire elemental",
  noun: "",
  url: "https://gswiki.play.net/fire_elemental",
  picture: "",
  level: 60,
  family: "Elemental",
  type: "Elemental",
  undead: false,
  blood: false,
  bones: nil,
  witherable: false,
  sympathy: true,
  muggable: nil,
  boss: false,
  otherclass: [
    "Extraplanar",
    "Magical"
  ],
  bcs: true,
  max_hp: 260,
  speed: nil,
  height: 6,
  size: "medium",
  areas: [
    {
      name: "Eye of V'Tull",
      uids: [3060002..3060018, 3061001..3061028]
    }
  ],
  attack_attributes: {
    physical_attacks: [
      {
        name: "Ensnare",
        as: 346
      }
    ],
    bolt_spells: [],
    warding_spells: [],
    offensive_spells: [
      {
        name: "Major Elemental Wave"
      }
    ],
    maneuvers: [],
    special_abilities: [],
    special_notes: []
  },
  defense_attributes: {
    asg: "10N",
    immunities: [],
    melee: (391..412),
    ranged: nil,
    bolt: 282,
    udf: 346,
    bar_td: nil,
    cle_td: nil,
    emp_td: 234,
    pal_td: nil,
    ran_td: nil,
    sor_td: (248..260),
    wiz_td: nil,
    mje_td: nil,
    mne_td: nil,
    mjs_td: nil,
    mns_td: (240..246),
    mnm_td: 200,
    defensive_spells: [],
    defensive_abilities: [],
    special_defenses: []
  },
  special_other: nil,
  abilities: [],
  alchemy: [],
  abilities_misc: [],
  equipment: [],
  treasure: {
    coins: nil,
    magic_items: nil,
    gems: nil,
    boxes: nil,
    skin: nil,
    other: nil
  },
  messaging: {
    description: [
      "The fire elemental is a massing of flames that flow and flicker with a life of their own. The intense heat generated by the fire elemental is nearly unbearable."
    ],
    arrival: [],
    flee: [],
    death: [
      "The fire elemental sputters violently, cascading flames all around as it collapses in a final fiery display."
    ],
    decay: [],
    search: [],
    spell_prep: [],
    attack: [
      "A fire elemental flares brighter, an extension reaching towards you!",
      "A fire elemental flares brightly, extending a fiery tendril towards you!",
      "A fire elemental focuses {pronoun} energies at you!"
    ],
    bite: [],
    claw: [],
    info: {
      general: [],
      class_tips: {
        cleric: [],
        paladin: [],
        ranger: [],
        bard: [],
        wizard: [],
        empath: [],
        rogue: [],
        warrior: [],
        sorcerer: []
      },
      miscellany: []
    },
    triggers: {}
  }
}
