{
  schema_version: 3,
  name: "lesser ice elemental",
  noun: "",
  url: "https://gswiki.play.net/lesser_ice_elemental",
  picture: "",
  level: 53,
  family: "Elemental",
  type: "Elemental",
  undead: false,
  blood: false,
  bones: false,
  witherable: false,
  sympathy: true,
  muggable: nil,
  boss: false,
  otherclass: [
    "Extraplanar",
    "Magical"
  ],
  bcs: true,
  max_hp: 400,
  speed: nil,
  height: 5,
  size: "large",
  areas: [
    {
      name: "Great Mountain Aenatumgana",
      uids: [4561102..4561141]
    }
  ],
  attack_attributes: {
    physical_attacks: [
      {
        name: "Ensnare"
      },
      {
        name: "Lash",
        as: 301
      }
    ],
    bolt_spells: [
      {
        name: "Minor Cold (1709)",
        as: 251
      }
    ],
    warding_spells: [],
    offensive_spells: [
      {
        name: "Elemental Dispel (417)"
      },
      {
        name: "Elemental Wave (410)"
      },
      {
        name: "Major Elemental Wave (435)"
      }
    ],
    maneuvers: [
      {
        name: "Ground Slam"
      }
    ],
    special_abilities: [],
    special_notes: []
  },
  defense_attributes: {
    asg: nil,
    immunities: [],
    melee: (297..386),
    ranged: nil,
    bolt: (256..302),
    udf: 416,
    bar_td: nil,
    cle_td: nil,
    emp_td: (203..204),
    pal_td: nil,
    ran_td: nil,
    sor_td: (216..223),
    wiz_td: nil,
    mje_td: (216..240),
    mne_td: nil,
    mjs_td: nil,
    mns_td: nil,
    mnm_td: nil,
    defensive_spells: [
      "Elemental Defense I (401)",
      "Elemental Defense II (406)",
      "Elemental Defense III (414)",
      "Prismatic Guard (905)"
    ],
    defensive_abilities: [],
    special_defenses: []
  },
  special_other: nil,
  abilities: [],
  alchemy: [],
  abilities_misc: [],
  equipment: [],
  treasure: {
    coins: nil,
    magic_items: nil,
    gems: nil,
    boxes: nil,
    skin: nil,
    other: nil
  },
  messaging: {
    description: [
      "The ice elemental is an amorphous conglomeration of ice and snow that writhes and moves about with a mind of its own. The intense cold generated by the ice elemental is nearly unbearable."
    ],
    arrival: [],
    flee: [],
    death: [],
    decay: [],
    search: [],
    spell_prep: [],
    attack: [
      "A lesser ice elemental lashes out at you!",
      "A lesser ice elemental releases a wave of cold blue energy at you!"
    ],
    bite: [],
    claw: [],
    info: {
      general: [],
      class_tips: {
        cleric: [],
        paladin: [],
        ranger: [],
        bard: [],
        wizard: [],
        empath: [],
        rogue: [],
        warrior: [],
        sorcerer: []
      },
      miscellany: []
    },
    triggers: {}
  }
}
