{
  schema_version: 3,
  name: "major glacei",
  noun: "",
  url: "https://gswiki.play.net/major_glacei",
  picture: "",
  level: 47,
  family: "Elemental",
  type: "Elemental",
  undead: false,
  blood: false,
  bones: false,
  witherable: false,
  sympathy: true,
  muggable: nil,
  boss: false,
  otherclass: [
    "Magical"
  ],
  bcs: true,
  max_hp: 240,
  speed: nil,
  height: 5,
  size: "medium",
  areas: [
    {
      name: "Great Mountain Aenatumgana",
      uids: [4561001..4561010]
    },
    {
      name: "Pinefar Forests",
      uids: [4563034..4563051]
    }
  ],
  attack_attributes: {
    physical_attacks: [
      {
        name: "Lash",
        as: 259
      },
      {
        name: "Strike",
        as: 281
      }
    ],
    bolt_spells: [
      {
        name: "Major Cold (907)",
        as: 212
      }
    ],
    warding_spells: [],
    offensive_spells: [],
    maneuvers: [],
    special_abilities: [],
    special_notes: []
  },
  defense_attributes: {
    asg: nil,
    immunities: [],
    melee: (123..265),
    ranged: (145..178),
    bolt: (145..178),
    udf: 324,
    bar_td: (172..211),
    cle_td: (180..189),
    emp_td: 173,
    pal_td: (150..155),
    ran_td: nil,
    sor_td: (191..200),
    wiz_td: nil,
    mje_td: (206..212),
    mne_td: nil,
    mjs_td: nil,
    mns_td: (177..186),
    mnm_td: (155..165),
    defensive_spells: [],
    defensive_abilities: [],
    special_defenses: []
  },
  special_other: nil,
  abilities: [],
  alchemy: [],
  abilities_misc: [],
  equipment: [],
  treasure: {
    coins: nil,
    magic_items: nil,
    gems: true,
    boxes: nil,
    skin: nil,
    other: nil
  },
  messaging: {
    description: [
      "The major glacei is a conglomeration of ice and snow that writhes and moves with a mind of its own formed in a vaguely humanoid shape. The cold generated by the major glacei is nearly unbearable."
    ],
    arrival: [],
    flee: [],
    death: [],
    decay: [],
    search: [],
    spell_prep: [],
    attack: [
      "A major glacei focuses a wave of cold energy at you!",
      "A major glacei lashes out at you!",
      "A major glacei strikes at you!"
    ],
    bite: [],
    claw: [],
    info: {
      general: [],
      class_tips: {
        cleric: [],
        paladin: [],
        ranger: [],
        bard: [],
        wizard: [],
        empath: [],
        rogue: [],
        warrior: [],
        sorcerer: []
      },
      miscellany: []
    },
    triggers: {}
  }
}
