{
  schema_version: 3,
  name: "minor glacei",
  noun: "",
  url: "https://gswiki.play.net/minor_glacei",
  picture: "",
  level: 42,
  family: "Elemental",
  type: "Elemental",
  undead: false,
  blood: false,
  bones: false,
  witherable: false,
  sympathy: true,
  muggable: nil,
  boss: false,
  otherclass: [
    "Magical"
  ],
  bcs: true,
  max_hp: nil,
  speed: nil,
  height: 5,
  size: "medium",
  areas: [
    {
      name: "Pinefar Forests",
      uids: [4563030..4563043]
    }
  ],
  attack_attributes: {
    physical_attacks: [
      {
        name: "Lash",
        as: (217..246)
      },
      {
        name: "Strike",
        as: (247..250)
      }
    ],
    bolt_spells: [],
    warding_spells: [],
    offensive_spells: [],
    maneuvers: [],
    special_abilities: [],
    special_notes: []
  },
  defense_attributes: {
    asg: nil,
    immunities: [],
    melee: (148..236),
    ranged: nil,
    bolt: nil,
    udf: nil,
    bar_td: 158,
    cle_td: (152..159),
    emp_td: 160,
    pal_td: (139..142),
    ran_td: nil,
    sor_td: (168..177),
    wiz_td: nil,
    mje_td: nil,
    mne_td: 158,
    mjs_td: nil,
    mns_td: (158..165),
    mnm_td: (131..141),
    defensive_spells: [],
    defensive_abilities: [],
    special_defenses: []
  },
  special_other: nil,
  abilities: [],
  alchemy: [],
  abilities_misc: [],
  equipment: [],
  treasure: {
    coins: nil,
    magic_items: nil,
    gems: true,
    boxes: nil,
    skin: nil,
    other: nil
  },
  messaging: {
    description: [
      "The minor glacei is a conglomeration of ice and snow that writhes and moves with a mind of its own formed in a vaguely humanoid shape. The cold generated by the minor glacei is nearly unbearable."
    ],
    arrival: [],
    flee: [],
    death: [],
    decay: [],
    search: [],
    spell_prep: [],
    attack: [
      "A minor glacei lashes out at you!",
      "A minor glacei strikes at you!"
    ],
    bite: [],
    claw: [],
    info: {
      general: [],
      class_tips: {
        cleric: [],
        paladin: [],
        ranger: [],
        bard: [],
        wizard: [],
        empath: [],
        rogue: [],
        warrior: [],
        sorcerer: []
      },
      miscellany: []
    },
    triggers: {}
  }
}
