# frozen_string_literal: true

# Generates the game sections of lib/common/map/map_crossings.rb from the
# StringProcs that neither the recognizers nor hand-authored manual schema
# cover: each remaining proc body is relocated VERBATIM into a named block in
# reviewed Lich code, and a matching
#   { "strategy" => "unique_crossing", "name" => ... }
# entry is merged into the game's manual conversions file. The code is moved,
# not rewritten - no semantic drift - and the mapdb keeps only the name.
#
#   ruby tools/gen_crossings.rb --in MAP.json [--game gs|dr]
#
# The file holds one marked section per game; a run regenerates only its own
# game's section. Regeneration is idempotent: an edge whose manual entry
# already references a unique_crossing gets its block rebuilt under the same
# name from the proc body in the input map.

require 'json'
require 'optparse'
require_relative 'mapdb_convert'

options = { game: 'gs' }
OptionParser.new do |opts|
  opts.on('--in FILE') { |v| options[:in] = v }
  opts.on('--game GAME', 'gs (default) or dr - selects name prefix and manual file') { |v| options[:game] = v }
end.parse!
abort 'missing --in' unless options[:in]
abort 'game must be gs or dr' unless %w[gs dr].include?(options[:game])

# GS keeps the original unprefixed names (already referenced by published
# data); DR names carry a prefix since GS and DR room ids overlap.
name_prefix = options[:game] == 'gs' ? 'crossing' : 'crossing_dr'
manual_name = options[:game] == 'gs' ? 'mapdb_manual_conversions.json' : 'mapdb_manual_conversions_dr.json'
manual_path = File.expand_path(manual_name, __dir__)
File.write(manual_path, JSON.generate({ 'wayto' => {}, 'timeto' => {} })) unless File.exist?(manual_path)
crossings_path = File.expand_path('../lib/common/map/map_crossings.rb', __dir__)

converter = MapdbConverter.new
converter.load_manual(manual_path)
manual = JSON.parse(File.read(manual_path))
map = JSON.parse(File.read(options[:in]))

bodies = {} # body => { name:, edges: [] }
map.each do |room|
  (room['wayto'] || {}).each do |dest, value|
    next unless value.is_a?(String) && value.start_with?(';e ')
    body = value[3..]
    next if converter.convert_wayto(body)

    existing = manual['wayto']["#{room['id']}:#{dest}"]
    if existing.is_a?(Hash) && existing['strategy'] == 'unique_crossing'
      entry = (bodies[body] ||= { name: existing['name'], edges: [] })
      entry[:name] ||= existing['name']
      entry[:edges] << "#{room['id']}:#{dest}"
    elsif existing.nil?
      (bodies[body] ||= { name: nil, edges: [] })[:edges] << "#{room['id']}:#{dest}"
    end
    # any other manual entry: hand-authored schema wins, no crossing needed
  end
end

# Crossings that replay a player's own configured commands cannot become
# schema by design - the whole point is that the content is theirs. Sort them
# last so the blocks still being worked on stay together at the top.
USER_SPECIFIC = /UserVars\.\w+\.each|UserVars\.Peregrine/

# sort_by is not stable in Ruby, and reshuffling the rest would make every
# regeneration a noisy diff - partition instead.
regular, user_specific = bodies.partition { |body, _| body !~ USER_SPECIFIC }
ordered = regular + user_specific

defs = +''
user_section_started = false
ordered.each do |body, info|
  if body =~ USER_SPECIFIC && !user_section_started
    user_section_started = true
    defs << "\n        # --- Player-configured command replays: these stay code by design. ---\n"
  end
  info[:name] ||= "#{name_prefix}_#{info[:edges].first.sub(':', '_')}"
  info[:edges].each do |key|
    manual['wayto'][key] = { 'strategy' => 'unique_crossing', 'name' => info[:name] }
  end
  defs << "\n        define('#{info[:name]}') do # #{info[:edges].join(' ')}\n"
  defs << body.gsub(/^/, '          ').rstrip
  defs << "\n        end\n"
end

header = <<~'HEADER'
  # frozen_string_literal: true

  # rubocop:disable all
  # One-off travel crossings relocated verbatim from mapdb StringProcs.
  #
  # GENERATED by tools/gen_crossings.rb - each block below is the exact Ruby
  # a map edge used to carry as an eval'd string. Living here it is reviewed,
  # diffable Lich code; the mapdb references it by name via
  #   { "strategy" => "unique_crossing", "name" => "crossing[_dr]_ROOM_DEST" }
  # Sections are per-game; a generator run replaces only its own section.
  # Refactor blocks into proper strategies at leisure.

  module Lich
    module Common
      module MapEngine
        module UniqueCrossings
          REGISTRY = {} unless const_defined?(:REGISTRY, false)

          def self.define(name, &block)
            REGISTRY[name.to_s] = block
          end

          def self.known?(name)
            REGISTRY.key?(name.to_s)
          end

          def self.run(name)
            block = REGISTRY[name.to_s]
            raise StepFailed, "unknown crossing #{name.inspect}" unless block
            block.call
            true
          end
HEADER

footer = <<~'FOOTER'
        end
      end
    end
  end
  # rubocop:enable all
FOOTER

section_begin = "        # ===== BEGIN #{options[:game]} crossings (generated) =====\n"
section_end   = "        # ===== END #{options[:game]} crossings =====\n"
section = section_begin + defs + section_end

if File.exist?(crossings_path)
  content = File.read(crossings_path)
  if content.include?(section_begin)
    # Block form: relocated proc bodies contain \1, \0, \\ and friends, which
    # String#sub would read as backreferences in a string replacement.
    content = content.sub(/#{Regexp.escape(section_begin)}.*?#{Regexp.escape(section_end)}/m) { section }
  else
    content = content.sub(footer) { section + footer }
  end
else
  content = header + "\n" + section + footer
end
File.write(crossings_path, content)
File.write(manual_path, JSON.pretty_generate(manual))
puts "#{options[:game]}: #{bodies.size} crossings (#{bodies.values.sum { |i| i[:edges].size }} edges); section rewritten"
