# frozen_string_literal: true

# Generates lib/<game>/map/map_crossings.rb from the StringProcs that neither
# the recognizers nor the manual schema cover: each remaining proc body is
# relocated VERBATIM into a named block in reviewed Lich code, and a matching
# {"strategy" => "unique_crossing", "name" => ...} entry is merged into the
# manual conversions file. The code is moved, not rewritten - no semantic
# drift - and the mapdb keeps only the name.
#
#   ruby tools/gen_crossings.rb --in MAP.json
#
# Regenerate whenever a new one-off proc appears; refactor individual
# crossings into proper strategies at leisure.

require 'json'
require 'optparse'
require_relative 'mapdb_convert'

options = { game: 'gs' }
OptionParser.new do |opts|
  opts.on('--in FILE') { |v| options[:in] = v }
  opts.on('--game GAME', 'gs (default) or dr - selects output file, name prefix, and manual file') do |v|
    options[:game] = v
  end
end.parse!
abort 'missing --in' unless options[:in]
abort 'game must be gs or dr' unless %w[gs dr].include?(options[:game])

# GS keeps the original unprefixed names (already referenced by published
# data); DR names carry a prefix since GS and DR room ids overlap.
game_dir = { 'gs' => 'gemstone', 'dr' => 'dragonrealms' }.fetch(options[:game])
name_prefix = options[:game] == 'gs' ? 'crossing' : 'crossing_dr'
manual_name = options[:game] == 'gs' ? 'mapdb_manual_conversions.json' : 'mapdb_manual_conversions_dr.json'
manual_path = File.expand_path(manual_name, __dir__)
File.write(manual_path, JSON.generate({ 'wayto' => {}, 'timeto' => {} })) unless File.exist?(manual_path)
crossings_path = File.expand_path("../lib/#{game_dir}/map/map_crossings.rb", __dir__)

converter = MapdbConverter.new
converter.load_manual(manual_path)
map = JSON.parse(File.read(options[:in]))

bodies = {} # body => [edge keys]
map.each do |room|
  (room['wayto'] || {}).each do |dest, value|
    next unless value.is_a?(String) && value.start_with?(';e ')
    body = value[3..]
    next if converter.convert_wayto(body) || converter.manual_for('wayto', room['id'], dest)
    (bodies[body] ||= []) << "#{room['id']}:#{dest}"
  end
end

manual = JSON.parse(File.read(manual_path))
defs = +''
bodies.each do |body, edges|
  name = "#{name_prefix}_#{edges.first.sub(':', '_')}"
  edges.each { |key| manual['wayto'][key] = { 'strategy' => 'unique_crossing', 'name' => name } }
  defs << "\n        define('#{name}') do # #{edges.join(' ')}\n"
  defs << body.gsub(/^/, '          ').rstrip
  defs << "\n        end\n"
end

File.write(crossings_path, <<~'HEADER' + defs + <<~'FOOTER')
  # frozen_string_literal: true

  # rubocop:disable all
  # One-off travel crossings relocated verbatim from mapdb StringProcs.
  #
  # GENERATED by tools/gen_crossings.rb - each block below is the exact Ruby
  # a map edge used to carry as an eval'd string. Living here it is reviewed,
  # diffable Lich code; the mapdb references it by name via
  #   { "strategy" => "unique_crossing", "name" => "crossing_ROOM_DEST" }
  # Refactor blocks into proper strategies at leisure; regenerate when a new
  # one-off proc appears in an unconverted map.

  module Lich
    module Common
      module MapEngine
        module UniqueCrossings
          REGISTRY = {} unless const_defined?(:REGISTRY, false)

          def self.define(name, &block)
            REGISTRY[name.to_s] = block
          end

          def self.known?(name)
            REGISTRY.key?(name.to_s)
          end

          def self.run(name)
            block = REGISTRY[name.to_s]
            raise StepFailed, "unknown crossing #{name.inspect}" unless block
            block.call
            true
          end
HEADER
        end
      end
    end
  end
  # rubocop:enable all
FOOTER

File.write(manual_path, JSON.pretty_generate(manual))
puts "wrote #{bodies.size} crossings (#{bodies.values.sum(&:size)} edges) to map_crossings.rb; manual file updated"
